config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "sales_and_repairs/index"
  get 'products/index'
  get "account/index"


  root :to => "sales_and_repairs#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'sales_and_repairs#index', :constraints => lambda { |request| request.env['warden'].user.role == ('proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :office_expenses do
    match "/scope_to_date" => "office_expenses#scope_to_date",  via: [:get], on: :collection
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/catering" => "orders#catering", as: :catering, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
    match "/sales_and_repairs" => "orders#sales_and_repairs", as: :sales_and_repairs, via: [:get], on: :collection
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :customers
    resources :interests, only: [:new, :create], module: :customers

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]
    resources :sales_entries, only: [:new, :create]
    resources :expense_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :sales_returns, only: [:new, :destroy]

  resources :service_fees, module: :service_charges
  resources :service_charges
end

app/controllers/products/barcodes_controller.rb
module Products
  class BarcodesController < ApplicationController
    def new
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.build
    end

    def create
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.create(barcode_params)
    end

    def edit
      @product = Product.find(params[:product_id])
      @barcode = Barcode.find(params[:id])
    end

    def update
      @product = Product.find(params[:product_id])
      @barcode = @product.barcodes.find(params[:id])
      @barcode.update(barcode_params)
    end

    def destroy
      @product = Product.find(params[:product_id]) if params[:product_id].present?
      @barcode = Barcode.find(params[:id])
      @barcode.destroy
      redirect_to barcode_product_path(@product), alert: 'Barcode deleted successfully.'
    end
    
    private
    def barcode_params
      params.require(:barcode).permit(:code)
    end
  end
end

app/controllers/products/stocks_controller.rb
module Products
  class StocksController < ApplicationController
    def new
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.build
    end

    def create
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.create(stock_params)
      @stock.employee = current_user
      if @stock.save
        redirect_to stock_histories_product_path(@product), notice: "New stock saved successfully."
        @stock.create_entry
        @stock.set_status_to_product
        @stock.purchased!
      else
        render :new
      end
    end

    def edit
      @product = Product.find(params[:product_id])
      @stock = Stock.find(params[:id])
    end

    def update
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:id])
      if @stock.update(stock_params)
        @stock.update_entry
        redirect_to stock_histories_product_path(@product), notice: "New stock saved successfully."
      end
    end

    def show
      @product = Product.find(params[:product_id])
      @stock = @product.stocks.find(params[:id])
    end

    def destroy
      @product = Product.find(params[:product_id]) if params[:product_id].present?
      @stock = Stock.find(params[:id])
      if @stock.line_items.blank?
        @stock.destroy
        if request.referer == stock_histories_product_url(@product)
          redirect_to stock_histories_product_path(@product), alert: 'Stock deleted successfully.'
        else
          redirect_to stocks_path, alert: "Stock deleted successfully."
        end
      else
        if request.referer == stock_histories_product_url(@product)
          redirect_to stock_histories_product_path(@stock), alert: "Unable to delete stock because there are orders associated with it. Discontinue instead!"
        else
          redirect_to stocks_path, alert: "Unable to delete stock because there are orders associated with it. Discontinue instead!"
        end
      end
    end
    
    private
    def stock_params
      params.require(:stock).permit(:has_freight, :freight_amount, :payment_type, :supplier_id, :reference_number, :quantity, :date, :total_cost, :unit_cost, :retail_price)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  autocomplete :product, :name_and_description, full: true

  def index
    if params[:name_and_description].present?
      @products = Product.search_by_name(params[:name_and_description]).page(params[:page]).per(30)
    else
      @products = Product.order(:name).page(params[:page]).per(30)
      respond_to do |format|
        format.html
        format.pdf do
          pdf = ProductsPdf.new(@products, view_context)
                send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Products Report.pdf"
        end
      end
    end
    authorize Product
  end

  def import
    begin
      Product.import(params[:file])
      redirect_to settings_url, notice: 'Products Imported'
    rescue
      redirect_to settings_url, notice: 'Invalid CSV File.'
    end
  end

  def download
    @categories = Category.order(:name).all
    @products = Product.available.order(:name)
    respond_to do |format|
      format.xlsx { render xlsx: "download", disposition: 'inline', filename: "products-#{Time.zone.now.strftime('%B %e, %Y')}" }
    end
  end

  def export
    @categories = Category.order(:name).all
    @products = Product.available.order(:name)
    respond_to do |format|
      format.xlsx { render xlsx: "export", disposition: 'inline', filename: "ProductsExport-#{Time.zone.now.strftime('%B %e, %Y')}" }
    end
  end

  def new
    @product = Product.new
    @product.stocks.build
    authorize @product
  end

  def create
    @products = Product.all
    @product = Product.create(product_params)
    @product.set_status
  end

  def barcode
    @product = Product.find(params[:id])
    @codes = @product.barcodes.all
    @barcodes = Kaminari.paginate_array(@codes).page(params[:page]).per(50)
  end

  def stock_histories
    @product = Product.find(params[:id])
    @available = @product.stocks.order(date: :desc)
    @stocks = Kaminari.paginate_array(@available).page(params[:page]).per(50)
  end

  def cash_sales
    @product = Product.find(params[:id])
    @sales = @product.line_items.cash
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end

  def credit_sales
    @product = Product.find(params[:id])
    @sales = @product.line_items.credit
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    @product.set_status
    @product.update_prices
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.orders.blank?
      @product.destroy
      redirect_to products_path, notice: 'Product deleted.'
    else
      redirect_to stock_histories_product_path(@product), notice: 'Product has orders, unable to delete.'
    end
  end

  def reports
    @product = Product.find(params[:id])
    @sales = @product.line_items.credit
    @results = Kaminari.paginate_array(@sales).page(params[:page]).per(50)
  end
  
  def scope_to_date_cash_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.now.yesterday.end_of_day
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.now.end_of_day
    @line_items = @product.line_items.cash.select{|a| a.created_at.between?(@from_date, @to_date) }
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Products::SalesReportPdf.new(@product, @line_items, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end
  def scope_to_date_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.zone.now
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.zone.now
    @line_items = @product.line_items.all.created_between({from_date: @from_date, to_date: @to_date})
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Products::SalesReportPdf.new(@product, @line_items, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end

  def scope_to_date_credit_sales
    @product = Product.find(params[:id])
    @from_date = params[:from_date] ? DateTime.parse(params[:from_date]) : Time.now.yesterday.end_of_day
    @to_date = params[:to_date] ? DateTime.parse(params[:to_date]) : Time.now.end_of_day
    @orders = @product.line_items.credit.all.created_between({from_date: @from_date, to_date: @to_date})
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrdersPdf.new(@orders, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Sales Report.pdf"
      end
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :unit, :retail_price, :stock_alert_count)
  end
end

app/views/products/histories/_barcode.html.erb
<div class="tab-pane <%='active' if current_page? barcode_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @barcodes.each do |barcode| %>
        <tr>
          <td><%=barcode.code %></td>
          <td>
            <%= link_to "Edit", edit_product_barcode_path(product_id: @product.id, id: barcode.id), class: 'btn btn-success btn-xs', remote: true %>
            &nbsp &nbsp &nbsp
            <%= link_to "Delete", product_barcode_path(product_id: @product.id, id: barcode.id), method: :delete, data: {confirm: "Are you sure to delete this barcode?" }, class: 'btn btn-danger btn-xs' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @barcodes, :window => 1 %></center>
  </div>
</div>
<div id="barcode-modal" class="modal fade"></div>

app/views/products/histories/_cash_sales.html.erb
<div class="tab-pane <%='active' if current_page? cash_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>S/N </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      </tr>
    </thead>
    <tbody>
      <% @results.to_a.sort_by(&:order_date).reverse.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:customer)%></td>
          <td><%=line_item.quantity %> <%=line_item.stock.product.unit %></td>
          <td><%=line_item.stock.serial_number %></td>
          <td><%=number_to_currency line_item.unit_price %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_credit_sales.html.erb
<div class="tab-pane <%='active' if current_page? credit_sales_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Customer </th>
        <th>QTY </th>
        <th>S/N </th>
        <th>Unit Cost </th>
        <th>Total Sales</th>
        <th>Cost of Goods Sold</th>
        <!-- <th> Income </th> -->

      
      </tr>
    </thead>
    <tbody>
      <% @results.each do |line_item| %>
        <tr>
        <% if line_item.order.present? %>
          <td><%=line_item.order.date.strftime("%B %e, %Y") %></td>
          <td><%=line_item.order.try(:customer)%></td>
          <td><%=line_item.quantity %> <%=line_item.stock.product.unit %></td>
          <td><%=line_item.stock.serial_number %></td>
          <td><%=number_to_currency line_item.unit_price %></td>
          <td><%=number_to_currency line_item.total_price %></td>
          <td><%=number_to_currency line_item.cost_of_goods_sold %></td>
          <!-- <td><%=number_to_currency line_item.income %></td> -->

        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @results, :window => 1 %></center>
  </div>
</div>

app/views/products/histories/_stock_histories.html.erb
<div class="tab-pane <%='active' if current_page? stock_histories_product_path %>">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Purchase Date</th>
        <th></th>
        <th>Qty </th>
        <th> Sold </th>
        <th> In Stock </th>
        <th>Unit</th>
        <th> Supplier</th>
        <th> Unit Cost </th>
        <th> Total Purchase </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@stocks.each do |stock| %>
        <tr>
          <td><%=link_to stock.date.strftime('%B %e, %Y'), product_stock_path(product_id: @product.id, id: stock.id), remote: true %></td>
          <td>
            <small class='label label-<%="danger" if stock.out_of_stock?%><%= "warning" if stock.low_stock?%><%= "danger" if !stock.low_stock?%><%= "danger" if stock.low_stock?%><%= "danger" if stock.returned_or_out_of_stock?%><%= "danger" if stock.discontinued_or_out_of_stock?%>'><%=stock.status %></small>
          </td>
          <td><%=stock.quantity %></td>
          <td><%=stock.sold %></td>
           <td><%=stock.in_stock %></td>
          <td><%=stock.product.unit %></td>
          <td><%=stock.supplier.business_name %></td>
          <td><%= number_to_currency stock.unit_cost %></td>
          <td><%=number_to_currency stock.total_cost %></td>
          <td class="pull-right">
            <%= link_to "Details", product_stock_path(product_id: @product.id, id: stock.id), class: 'btn btn-xs btn-info' %>
            &nbsp&nbsp
            <%= link_to "Edit", edit_product_stock_path(product_id: @product.id, id: stock.id), class: "btn btn-xs btn-warning" %>
            &nbsp&nbsp
            <%= link_to product_stock_path(product_id: @product.id, id: stock.id), method: :delete, title: 'Delete Stock', data: {confirm: 'Are you sure you want to delete this stock? This action can not be undone.'} do %>
              <span class="text-danger" title="Delete Stock" data-toggle='tooltip'><i class="fa fa-trash"></i></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <center><%= paginate @stocks, :window => 1 %></center>
  </div>
</div>
<div id="stock-show-modal" class="modal fade"></div>