config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "sales_and_repairs/index"
  get 'products/index'
  get "account/index"


  root :to => "sales_and_repairs#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'sales_and_repairs#index', :constraints => lambda { |request| request.env['warden'].user.role == ('proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :office_expenses do
    match "/scope_to_date" => "office_expenses#scope_to_date",  via: [:get], on: :collection
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/catering" => "orders#catering", as: :catering, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
    match "/sales_and_repairs" => "orders#sales_and_repairs", as: :sales_and_repairs, via: [:get], on: :collection
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :customers
    resources :interests, only: [:new, :create], module: :customers

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]
    resources :sales_entries, only: [:new, :create]
    resources :expense_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :sales_returns, only: [:new, :destroy]

  resources :service_fees, module: :service_charges
  resources :service_charges
end

app/models/accounting/amount.rb
module Accounting
  class Amount < ApplicationRecord
    belongs_to :account, class_name: "Accounting::Account"
    belongs_to :entry, class_name: "Accounting::Entry"

    validates :type, :amount, :entry, :account, presence: true

    def account_name=(name)
      self.account = Accounting::Account.find_by_name(name)
    end

    protected
    # Support constructing amounts with account = "name" syntax
    # def account_with_name_lookup=(v)
    #   if v.kind_of?(String)
    #     ActiveSupport::Deprecation.warn('Plutus was given an :account String (use account_name instead)', caller)
    #     self.account_name = v
    #   else
    #     self.account_without_name_lookup = v
    #   end
    # end
    # alias_method_chain :account=, :name_lookup
    
  end
end

app/models/accounting/amounts_extension.rb
module Accounting
  module AmountsExtension
    def balance(hash={})
      if hash[:from_date] && hash[:to_date]
        from_date = hash[:from_date].kind_of?(Time) ? hash[:from_date] : Time.parse(hash[:from_date].strftime('%Y-%m-%d 12:00:00 AM'))
        to_date = hash[:to_date].kind_of?(Time) ? hash[:to_date] : Time.parse(hash[:to_date].strftime('%Y-%m-%d 23:59:59 PM'))
        joins(:entry, :account).where('entries.date' => from_date..to_date).sum(:amount)
      else
        joins(:entry, :account).sum(:amount)
      end
    end

    def balance_for_new_record
      balance = BigDecimal.new('0')
      each do |amount_record|
        if amount_record.amount && !amount_record.marked_for_destruction?
          balance += amount_record.amount # unless amount_record.marked_for_destruction?
        end
      end
      return balance
    end
  end
end

app/models/accounting/credit_amount.rb
module Accounting
  class CreditAmount < Amount
  end
end

app/models/accounting/debit_amount.rb
module Accounting
  class DebitAmount < Amount
  end
end

app/controllers/accounting/accounting_controller.rb
class AccountingController < ApplicationController
  def index
  end
end 

app/controllers/accounting/accounts_controller.rb
module Accounting
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    before_action :set_type

    autocomplete :accounting_account, :name, full: true

    def index
      if params[:name].present?
        @accounts = type_class.search_by_name(params[:name])
      else
        @accounts = type_class.all.order(:code)
      end
      authorize @accounts
    end

    def show
    end

    def new
      @account = type_class.new
    end

    def edit
    end

    def create
      @accounts = Accounting::Account.all.order(:type)
      @account = Accounting::Account.create(account_params)
    end

    def update
      @accounts = Accounting::Account.all
      @account = Accounting::Account.find(params[:id])
      @account.update_attributes(account_params)
    end

    def activate
      @account = Accounting::Account.find(params[:id])
      @account.active!
      redirect_to accounting_index_url
    end
    def deactivate
      @account = Accounting::Account.find(params[:id])
      @account.inactive!
      redirect_to accounting_index_url
    end

    def destroy
      @account.destroy
      redirect_to accounts_url
    end

    private

    def set_type
      @type = type
    end

    def type
      Accounting::Account.types.include?(params[:type]) ? params[:type] : "Accounting::Account"
    end

    def type_class
      type.constantize
    end

    def set_account
      @account = type_class.find(params[:id])
    end

    def account_params
      params.require(type.underscore.gsub('/', '_').to_sym).permit(:name, :type, :code)
    end

  end
end

app/controllers/accounting/balance_sheets_controller.rb
module Accounting
  class BalanceSheetsController < ApplicationController
    def index
      first_entry = Accounting::Entry.order('date ASC').first
      @from_date = first_entry ? first_entry.date: Date.today
      @to_date = params[:date] ? Date.parse(params[:date]) : Date.today
      @assets = Accounting::Asset.active_with_balance
      @liabilities = Accounting::Liability.active_with_balance
      @equity = Accounting::Equity.active_with_balance
      @revenues = Accounting::Revenue.active_with_balance
      @expenses = Accounting::Expense.active_with_balance

      respond_to do |format|
        format.html # index.html.erb
      end
    end
    def scope_to_date
      first_entry = Accounting::Entry.order('date ASC').first
      @from_date = first_entry ? first_entry.date: Time.zone.now
      @to_date = params[:date] ? Date.parse(params[:date]) : Time.zone.now
      @assets = Accounting::Asset.all
      @liabilities = Accounting::Liability.all
      @equity = Accounting::Equity.all
      @revenues = Accounting::Revenue.all
      @expenses = Accounting::Expense.all

      respond_to do |format|
        format.html # index.html.erb
        format.pdf do
          pdf = Accounting::BalanceSheetPdf.new(@equity, @liabilities, @assets, @revenues, @expenses, @from_date, @to_date, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Balance Sheet.pdf"
        end
      end
    end
  end
end

app/controllers/accounting/consignments_controller.rb
module Accounting
  class ConsignmentsController < ApplicationController

  	def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entries = Accounting::Entry.all
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to stocks_path, notice: 'Entry for sales has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :entry_type, :commercial_document_id, :commercial_document_type, :description, :reference_number, debit_amounts_attributes:[:amount, :account_id], credit_amounts_attributes:[:amount, :account_id])
    end
  end
end

app/controllers/accounting/credit_payments_controller.rb
module Accounting
  class CreditPaymentsController < ApplicationController

    def new
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @line_item.order
      @entry.recorder = current_user
      if @entry.save
        @line_item.cash!
        redirect_to @line_item.stock.product, notice: "Payment saved successfully."
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/dashboard_controller.rb
module Accounting
  class DashboardController < ApplicationController
    def index
      authorize [:accounting, :dashboard]
    end
  end
end

app/controllers/accounting/expense_entries_controller.rb
module Accounting 
  class ExpenseEntriesController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to account_index_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/controllers/accounting/fund_transfers_controller.rb
module Accounting 
  class FundTransfersController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to account_index_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/views/accounting/entries/_index.html.erb
<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.date.strftime("%b %e, %Y - %I:%M %p") %></td>

    <td><%=link_to entry.description.truncate(200), accounting_entry_path(entry) %></td>
    <!-- <td><%#=entry.commercial_document || "Proprietor" %></td> -->
    <td><%=entry.recorder.try(:full_name) %></td>
    <td><%entry.debit_amounts.each do |debit| %>
      <small><%= debit.account.try(:name) %> <span class='pull-right'><%=number_to_currency debit.amount %></span></small><br>
      <% end %>
      </td>
       <td><%entry.credit_amounts.each do |credit| %>
      <small><%= credit.account.try(:name) %> <span class='pull-right'><%=number_to_currency credit.amount %></span></small><br>
      <% end %>
      </td>
  </tr>
<% end %>

app/views/accounting/entries/index.html.erb
<div id="entryModal" class="modal fade"></div>
<div class="row">
  <div class="col-md-12">
  	<div class="card">
    	<div class="card-header">
    		<div class="card-title">
    			<div class="row">
						<div class="col-md-4">
					  	<ul class="nav navbar-nav">
					      <li class="dropdown">
					        <button href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Show Activity <b class="caret"></b></button>
					        <ul class="dropdown-menu dropdown-menu-right">
					          <li><%=link_to 'This Day', scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') %></li>
								    <li> <%=link_to 'This Week', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') %></li>
								    <li> <%=link_to 'This Month', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') %></li>
					        </ul>
					      </li>
					    </ul>
						</div>
						<div class="col-md-4">
					    <%=form_tag accounting_entries_path, method: :get do %>
					      <div class="input-group stylish-input-group" id="entry-prefetch">
					        <%= autocomplete_field_tag "description", params[:description], autocomplete_entry_description_accounting_entries_path, class: 'form-control', placeholder: 'Search Entry...' %>
					        <span class="input-group-btn">
					          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
					            <i class="fa fa-search"></i>
					          <% end %>
					        </span>
					      </div>
					    <% end %>
						</div>
						<div class="col-md-4">
							<%=link_to 'New Entry', new_accounting_entry_path, class: 'btn btn-success pull-right' %>
						</div>
					</div>
					<br>
					<div class="row">
					  <div class="col-md-3">
					    <span class="pull-right title">Filter Date:</span>
					  </div>
					  <div class="col-md-9">
					    <%= form_tag({:action => 'index'}, {:method => :get})  do %>
					      <div class="row">
					        <div class="col-md-4">
					          <%= text_field_tag :from_date, @from_date, :class => 'datepicker-reporting form-control'%>
					        </div>
					        <div class="col-md-4">
					          <%= text_field_tag :to_date, @to_date, :class => 'form-control datepicker-reporting'%>
					        </div>
					        <div class="col-md-4">
					        	<button type="submit" class="btn btn-success active"> Go </button>
					        	<% if (params[:from_date] && params[:to_date]).present? %>
					          	<%=link_to "PDF", scope_to_date_accounting_entries_path(format: 'pdf', from_date: @from_date, to_date: @to_date), class: "btn btn-default active"%>
					          <% end %>
					        </div>
					      </div>
					    <% end %>
					  </div>
					</div>
				</div>
			</div>
			<div class="card-body">
				<div class="table table-responsive">
					<table class="table table-striped">
						<thead>
							<tr class="title">
                <th> Date </th>
								<th> Description </th>
                <!-- <th> Proprietor / Supplier </th> -->
								<th> Employee </th>
								<th> Debit</th>
								<th> Credit </th>
							</tr>
						</thead>
						<tbody class="entry-index">
							<%=render 'index' %>
						</tbody>
					</table>
					<div class="modal-footer">
	          <center>
	          		<%= paginate @entries, :window => 1 %>
	          </center>
	        </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/accounting/entries/new.html.erb
<%= simple_form_for @entry, html: { style: "display:inline;" } do |f| %>
<%=f.error_notification %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">New Entry</h4>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <%=f.input :reference_number %>
            </div>
            <div class="col-md-6">
              <%=f.input :date, as: :string, input_html: { class: "datepicker" } %>
            </div>
          </div>
          <%=f.input :description %>
          <%=f.simple_fields_for :debit_amounts do |ff| %>
            <%=ff.input :amount %>
            <%=ff.association :account, collection: Accounting::Account.active.all.map { |a| [a.name, a.id] }, label: 'Debit Account' %>
          <% end %>
          <%=f.simple_fields_for :credit_amounts do |ff| %>
            <%=ff.input :amount, as: :hidden %>
            <%=ff.association :account, collection: Accounting::Account.active.all.map { |a| [a.name, a.id] }, label: 'Credit Account' %>
          <% end %>
        </div>
        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", accounting_entries_path, class: "btn pull-left" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $("#accounting_entry_debit_amounts_attributes_0_account_id").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
  $("#accounting_entry_credit_amounts_attributes_0_account_id").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
</script>

app/views/accounting/entries/new.js.erb
$("#entryModal").html("<%= escape_javascript(render 'new') %>")
$('#entryModal').modal({backdrop: 'static', keyboard: false, show: true})
$('.datepicker').datepicker({
	format: "yyyy/mm/dd/",
	orientation: "auto bottom",
	todayHighlight: 'true',
	autoclose: 'true'
	});
$("#accounting_entry_debit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});
$("#accounting_entry_credit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});

app/views/accounting/entries/show.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="card">
			<div class="card-header">
				<div class="card-title">
					<h4>Entry Details</h4>
				</div>
			</div>
			<div class="card-body">
				<p><strong>Date</strong></p>
				<span>&nbsp &nbsp &nbsp<%=@entry.date.strftime("%B %e, %Y") %></span>
				<hr>
				<p><strong>Description</strong></p>
				<span>&nbsp &nbsp &nbsp<%=@entry.description %></span><br>
				<hr>
				<p><strong>Member/Employee/Supplier:</strong></p>
				<span>&nbsp &nbsp &nbsp<%=@entry.commercial_document.try(:full_name) %></span><br>
				<hr>
				<p><strong>Reference Number</strong></p>
				<span>&nbsp &nbsp &nbsp<%=@entry.reference_number%></span>
				<hr>
				<p><strong>Debited Account(s)</strong></p>
				<%@entry.debit_amounts.each do |d|%>
					<div class="row">
						<div class="col-md-12">
							&nbsp &nbsp &nbsp<%=d.account.name %><span class="pull-right"><%=number_to_currency d.amount %></span>
						</div>
					</div>
				<%end %>
				<hr>

				<p><strong>Credited Account(s)</strong></p>
				<%@entry.credit_amounts.each do |d|%>
					<div class="row">
						<div class="col-md-12">
							&nbsp &nbsp &nbsp<%=d.account.name %> <span class="pull-right"><%=number_to_currency d.amount %></span>
						</div>
					</div>
				<% end %>
				<br>
				<div class="modal-footer">
					<%= link_to "Back", accounting_entries_path, class: 'btn btn-default pull-left' %>
					<%=link_to 'Delete Entry', accounting_entry_path(@entry), method: :delete, data: {confirm: 'Are you sure you want to DELETE this entry? THIS ACTION CANNOT BE UNDONE.'}, class: 'text-danger' %>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="entryModal" class="modal fade"></div>