config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "sales_and_repairs/index"
  get 'products/index'
  get "account/index"


  root :to => "sales_and_repairs#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'sales_and_repairs#index', :constraints => lambda { |request| request.env['warden'].user.role == ('proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :office_expenses do
    match "/scope_to_date" => "office_expenses#scope_to_date",  via: [:get], on: :collection
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/catering" => "orders#catering", as: :catering, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
    match "/sales_and_repairs" => "orders#sales_and_repairs", as: :sales_and_repairs, via: [:get], on: :collection
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :customers
    resources :interests, only: [:new, :create], module: :customers

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]
    resources :sales_entries, only: [:new, :create]
    resources :expense_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :sales_returns, only: [:new, :destroy]

  resources :service_fees, module: :service_charges
  resources :service_charges
end

app/controllers/sales_and_repairs_controller.rb
class SalesAndRepairsController < ApplicationController

  def index
    if params[:name_and_description].present?
      @products = Product.search_by_name(params[:name_and_description]).pluck(:id)
      if @products.present?
        @stocks = Stock.order(date: :asc).joins(:product).where(products: { id: @products })
      else
        redirect_to caterings_path, notice: 'Product is either out of stock or expired.'
      end
    else
      @stocks = Stock.purchased.all
    end
    authorize :store
    @cart = current_cart
    @line_item = LineItem.new
    @order = Order.new
    @order.build_discount
  end
end

app/views/sales_and_repairs/index.html.erb
<div class="row">
  <div class="col-md-7">
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <div class="row">
            <div class="col-md-12">
              <span class="pull-right">
                <%= link_to "Add Repairs/Maintenance", new_service_fee_path, class: 'btn btn-warning', remote: true %>
              </span>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12">
              <% if params[:name_and_description].present? %>
                <%=form_tag sales_and_repairs_index_path, method: :get do %>
                  <div class="input-group" id="product-prefetch">
                    <%= autocomplete_field_tag "name_and_description", params[:name_and_description], autocomplete_product_name_and_description_products_path, class: 'form-control input-lg', placeholder: 'Search Items...' %>
                    <span class="input-group-btn">
                      <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                        <i class="fa fa-search"></i>
                      <% end %>
                    </span>
                  </div>
                <% end %>
              <% else %>
                <%=form_tag sales_and_repairs_index_path, method: :get do %>
                  <div class="input-group">
                    <%= autocomplete_field_tag "name_and_description", params[:name_and_description], autocomplete_product_name_and_description_products_path, autofocus: true, class: 'form-control input-lg', placeholder: 'Search Items...' %>
                    <span class="input-group-btn">
                      <%= button_tag(type: 'submit', class: "btn btn-flat btn-lg") do %>
                        <i class="fa fa-search"></i>
                      <% end %>
                    </span>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body">
          <% if params[:name_and_description].present? && @stocks.count > 0 %>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Product</th>
                  <th class="text-right" width="110px">Price </th>
                  <th class="text-center">QTY </th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @stocks.available.each do |stock| %>
                  <% if stock.out_of_stock? %>
                    <tr><td colspan="4" class="text-center text-muted"><h3>Out of Stock!</h3></td></tr>
                  <% else %>
                    <tr>
                      <td>
                        <h5><%=stock.product.name_and_description %></h5>
                        <p class="text-muted">Remaining: <%=stock.in_stock%> <%=stock.product.unit%></p>
                      </td>
                      <%=simple_form_for @line_item, url: :line_items do |f| %>
                      <%=f.error_notification %>
                      
                        <td width="120px">
                          <div class="pull-right"> 
                            <%=f.input :unit_price, input_html: { value: stock.product.retail_price}, label: false %>
                          </div>
                        </td>
                        <td width="120px">
                          <%=f.input :stock_id, input_html: {value: stock.id }, as: :hidden %>
                          <div class="pull-right">
                            <%=f.input :quantity, input_html: {value: 1, max: stock.quantity}, autofocus: true, label: false %>
                          </div>
                        </td>
                        <td width="60px">
                          <div class="pull-right">
                            <%=f.submit "Add", data: {disable_with: "Adding Product..."}, class: "btn btn-primary btn-sm active" %>
                          </div>
                        </td>
                      <% end %>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% elsif @stocks.count.zero? && params[:name_and_description].blank? %>
            <p class="alert alert-info"> Product not found or out of stock.<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> </p>
          <% end %>
        </div>
    </div>
    <div class="card">
      <div class="card-header">
        <div class="card-title">
          <h4 class="text-warning">Sales & Repairs 
            <span class="pull-right">
              <%= number_to_currency @cart.total_amount %>
            </span>
          </h4>
        </div>
      </div>
      <div class="card-body">
        <% if @cart.line_items.present? %>
          <h4>
            Items
            <span class="pull-right"><%= number_to_currency @cart.line_items_amount %></span>
          </h4>
          <hr>
          <%= render @cart.line_items.sort_by{|l| l.stock_name } %>
        <% end %>
        <% if @cart.service_charges.present? %>
          <h4>
            Additional Charges
            <span class="pull-right"><%= number_to_currency @cart.additional_charges_amount %></span>
          </h4>
          <hr>
          <%= render @cart.service_charges %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-5" id="cart">
    <% if @cart.items_and_repairs.present? %>
      <div class="card">
        <div class="card-body">
        <div id="member-modal" class="modal fade"></div>
          <div class="row">
            <div class="col-md-12">
              <div class="pull-left">
                <h2> <b>Sub Total</b> </h2>
              </div>
              <div class="pull-right">
                <h2><b><%=number_to_currency @cart.total_amount %></b></h2>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-12">
              <%=simple_form_for @order, url: :orders do |f| %>
                <span>
                  <label>Customer</label>
                  <span class="pull-right">
                    <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                      <button href="#" class="dropdown-toggle btn btn-success btn-xs" data-toggle="dropdown" aria-expanded="false">New Customer <b class="caret"></b></button>
                      <ul class="dropdown-menu dropdown-menu-right">
                        <li><%=link_to "Regular", new_member_path, remote: true %></li>
                        <li> <%=link_to 'Organization', new_organization_path, remote: true %></li>
                      </ul>
                    </li>
                  </ul>
                  </span>
                </span>
                <%=f.input :customer_id, label: false, collection: Customer.order(:id).all.map{|a| [a.full_name, a.id] }, default: Customer.find_by(first_name: "Guest"), input_html: {id: 'order_customer_id' }%>
                <input type="hidden" name="total" id="total" value="<%= @cart.total_amount %>" oninput="calculateChange()">
                <div class="row">
                  <div class="col-md-5">
                    <%=f.input :pay_type, collection: Order.pay_types.keys.to_a.map{|a| [a.titleize, a]}, selected: Order.pay_types.keys.first %>
                  </div>
                  <div class="col-md-7">
                    <%=f.input :date, as: :string, input_html: {class: 'datepicker', value: Time.zone.now.strftime("%Y-%m-%d %I:%M %p")} %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6">
                    <%=f.input :cash_tendered, input_html: {oninput: 'calculateChange()', class: 'input-lg'}, label: "Amount Tendered" %>
                  </div>
                  <div class="col-md-6">
                    <%=f.input :change, input_html: { class: 'input-lg'}, readonly: true %>
                  </div>
                </div>
                <hr>
                <br>
                <br>
                <%=f.submit "Checkout", class: 'btn btn-success btn-block btn-lg checkout' %>
                <br>
                <br>
                <br>
                <br>
              <% end %>
              <hr>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div id="organization-modal" class="modal fade"></div>
<div id="member-modal" class="modal fade"></div>
<div id="service-fee-modal" class="modal fade"></div>
<script>
  $(document).ready(function() {
    $("#order_customer_id").select2({
      theme: "bootstrap",
      width: "100%"
    });
  });
</script>
<!-- <script>
  $(document).ready(function(){
    $('.checkout').prop('disabled',true);
    $('#order_customer_id').change(function(){
      $('.checkout').prop('disabled', this.value == "" ? true : false);     
    })
  });
</script> -->
<!-- <script>
  var checkbox = document.getElementById('order_discount');
  var details_div = document.getElementById('discount_details');
  checkbox.onchange = function() {
     if(this.checked) {
       details_div.style['display'] = 'block';
     } else {
       details_div.style['display'] = 'none';
     }
  };
</script> -->