config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "sales_and_repairs/index"
  get 'products/index'
  get "account/index"


  root :to => "sales_and_repairs#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'sales_and_repairs#index', :constraints => lambda { |request| request.env['warden'].user.role == ('proprietor' || 'developer') if request.env['warden'].user }, as: :admin_root
  root :to => 'products#index', :constraints => lambda { |request| request.env['warden'].user.role == 'stock_custodian' if request.env['warden'].user }, as: :stock_custodian_root
  root :to => 'accounting/accounts#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bookkeeper' if request.env['warden'].user }, as: :bookkeeper_root

  resources :products do
    get :autocomplete_product_name_and_description, on: :collection
    match "/scope_to_category" => "products#scope_to_category", as: :scope_to_category, via: [:get], on: :collection
    resources :stocks, module: :products
    resources :barcodes, module: :products
    match "/cash_sales" => "products#cash_sales", as: :cash_sales, via: [:get], on: :member
    match "/credit_sales" => "products#credit_sales", as: :credit_sales, via: [:get], on: :member
    match "/stock_histories" => "products#stock_histories", as: :stock_histories, via: [:get], on: :member
    match "/barcode" => "products#barcode", as: :barcode, via: [:get], on: :member
    match "/reports" => "products#reports", as: :reports, via: [:get], on: :member
    match "/scope_to_date_cash_sales" => "products#scope_to_date_cash_sales",  via: [:get], on: :member
    match "/scope_to_date_credit_sales" => "products#scope_to_date_credit_sales",  via: [:get], on: :member
    match "/scope_to_date_sales" => "products#scope_to_date_sales",  via: [:get], on: :member
    collection { post :import}
    match "/download" => "products#download", as: :download, via: [:get], on: :collection
    match "/export" => "products#export", as: :export, via: [:get], on: :collection
  end
  resources :barcodes do
    collection { post :import}
  end

  resources :credit_collections do
    match "/scope_to_date" => "credit_collections#scope_to_date",  via: [:get], on: :collection
  end

  resources :office_expenses do
    match "/scope_to_date" => "office_expenses#scope_to_date",  via: [:get], on: :collection
  end

  resources :line_items do
    resources :credit_payments, only: [:new, :create], module: :accounting
    match "/return_line_item" => "line_items#return_line_item", as: :return_line_item, via: [:get, :post]
    match "/return" => "line_items#return", as: :return, via: [:get, :post]
  end

  resources :carts
  resources :orders do
    resources :sales_returns, only: [:destroy], module: :orders
    match "/guest" => "orders#guest",  via: [:post], on: :member
    match "/print" => "orders#print",  via: [:get], on: :member
    match "/print_invoice" => "orders#print_invoice",  via: [:get], on: :member
    match "/print_official_receipt" => "orders#print_official_receipt",  via: [:get], on: :member
    match "/scope_to_date" => "orders#scope_to_date",  via: [:get], on: :collection
    match "/scope_to_date_summary" => "orders#scope_to_date_summary",  via: [:get], on: :collection
    match "/catering" => "orders#catering", as: :catering, via: [:get], on: :collection
    match "/sales_returns" => "orders#sales_returns", as: :sales_returns, via: [:get], on: :collection
    match "/return" => "orders#return", as: :return, via: [:get, :post]
    match "/sales_and_repairs" => "orders#sales_and_repairs", as: :sales_and_repairs, via: [:get], on: :collection
  end

  resources :members, only: [:new, :create, :edit, :update]
  resources :organizations, only: [:new, :create, :edit, :update]
  resources :customers do
    collection { post :import}
    get :autocomplete_customer_full_name, on: :collection
    resources :payments, only: [:new, :create], module: :customers
    resources :interests, only: [:new, :create], module: :customers

    match "/info" => "customers#info", as: :info, via: [:get], on: :member
    match "/purchases" => "customers#purchases", as: :purchases, via: [:get], on: :member
    match "/account_details" => "customers#account_details", as: :account_details, via: [:get], on: :member
    match "/payments" => "customers#payments", as: :payments, via: [:get], on: :member

    resources :line_items, only: [:index], module: :customers do
      match "/scope_to_date" => "line_items#scope_to_date",  via: [:get], on: :collection, module: :customers
    end

    match "/export" => "customers#export", as: :export, via: [:get], on: :collection
  end
  
  resources :payables, only: [:index]
  resources :suppliers, :except => [:destroy] do
    get :autocomplete_supplier_owner, on: :collection
    resources :payments, only: [:new, :create], module: :suppliers
    match "/cash_stocks" => "suppliers#cash_stocks", as: :cash_stocks, via: [:get], on: :member
    match "/credit_stocks" => "suppliers#credit_stocks", as: :credit_stocks, via: [:get], on: :member
    match "/credit_payments" => "suppliers#credit_payments", as: :credit_payments, via: [:get], on: :member

  end
  resources :reports, only: [:index]
  resources :settings, only: [:index]
  resources :credits, only: [:index]
  namespace :accounts_receivables do
    resources :interests, only:[:create]
  end
  resources :available_products, only: [:index]

  resources :low_stock_products, only: [:index]
  resources :out_of_stock_products, only: [:index]
  resources :expired_products, only: [:index]


  resources :refunds, only: [:index, :new, :create]
  resources :taxes, only: [:new, :create]
  resources :stocks, only: [:index, :show, :new, :create, :destroy] do
    collection { post :import}
    get :autocomplete_stock_name, on: :collection
    match "/scope_to_date" => "stocks#scope_to_date",  via: [:get], on: :collection
    resources :refunds, only: [:new, :create], module: :stocks
    match "/out_of_stock" => "stocks#out_of_stock", via: [:get], on: :collection
    match "/returned" => "stocks#returned", via: [:get], on: :collection
    match "/discontinued" => "stocks#discontinued", via: [:get], on: :collection
    match "/discontinue" => "stocks#discontinue", as: :discontinue, via: [:get, :post]
    match "/continue" => "stocks#continue", as: :continue, via: [:get, :post]
    match "/export" => "stocks#export", as: :export, via: [:get], on: :collection
  end
  resources :users, only: [:show, :edit, :update] do 
    match "/info" => "users#info", as: :info, via: [:get], on: :member
    match "/activities" => "users#activities", as: :activities, via: [:get], on: :member
  end
  resources :employees, only: [:new, :create]
  resources :accounting, only: [:index] do
    get :autocomplete_account_name, on: :collection
  end
  namespace :accounting do
    resources :balance_sheets, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "balance_sheets#scope_to_date", via: [:get], on: :collection
    end
    resources :income_statements, only:[:index, :scope_to_date] do
      match "/scope_to_date" => "income_statements#scope_to_date", via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :fund_transfers, only: [:new, :create]
    resources :remittances, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]
    resources :sales_entries, only: [:new, :create]
    resources :expense_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
  end

  namespace :owner do
    resources :dashboard, only: [:index]
  end
  resources :sales_returns, only: [:new, :destroy]

  resources :service_fees, module: :service_charges
  resources :service_charges
end

app/controllers/accounting/reports_controller.rb
module Accounting
  class ReportsController < ApplicationController
    def index
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end
end 

app/views/reports/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success fresh-color">
      <div class="panel-heading">
        <h4>SALES</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.now.beginning_of_day, to_date: Time.now.end_of_day, format: 'pdf') do %>
              <h4> Daily Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4> Weekly Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_orders_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly Sales Report </h4>
              <p> Generate daily sales report for today. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-6 col-md-offset-3 ">
            <h4> Custom Sales Report </h4>
            <%= form_tag({:action => "scope_to_date", controller: "orders", format: 'pdf'}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker-reporting form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker-reporting', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-2">
                  <button type="submit" class="btn btn-success active"> Go </button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-danger">
      <div class="panel-heading">
        <h4>INVENTORIES</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to low_stock_products_path(format: 'pdf'), class: 'text-warning' do %>
              <h4><span class='text-danger'><i class='fa fa-file-text-o'></i> Low Stock Items </span> </h4>
              <p>Generate report for all low stock products. </p>
            <% end %>
            <hr >
          </div>
          <div class="col-md-4">
            <%=link_to expired_products_path(format: 'pdf'), class: 'text-danger' do %>
              <h4 class="text-danger"><i class='fa fa-file-text-o text-danger'></i> Expired Items </h4>
              <p>Generate report for expired products. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to out_of_stock_products_path(format: 'pdf'), class: 'text-danger' do %>
              <h4 class="text-danger"><i class='fa fa-file-text-o text-danger'></i> Out of Stock Items </h4>
              <p>Generate report for all out of stock products. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4 col-md-offset-4">
            <%=link_to products_path(format: 'pdf') do %>
              <h4 class="text-info"> Current Inventory Status </h4>
              <p class="category"> Generate current status of inventories. </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-warning">
      <div class="panel-heading">
        <h4>PURCHASES</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_day, to_date: Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4> Daily Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4> Weekly Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_stocks_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly Purchase </h4>
              <p> Generate report for purchases entered this day. </p>
            <hr>
            <% end %>
          </div>
          <div class="col-md-6 col-md-offset-3">
            <h4> Custom Purchases Report </h4>
            <%= form_tag({:action => "scope_to_date", controller: "stocks", format: 'pdf'}, {:method => :get})  do %>
              <div class="row">
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :from_date, @from_date, :class => 'datepicker-reporting form-control border-input', :placeholder => "From " %>
                  </div>
                </div>
                <div class="col-md-5">
                  <div class="form-group">
                    <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker-reporting', :placeholder => "To " %>
                  </div>
                </div>
                <div class="col-md-2">
                  <button type="submit" class="btn btn-success active"> Go </button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>RECEIVABLES</h4>
      </div>
      <div class="panel-body">
        <%=link_to credits_path(format: 'pdf') do %>
          <h4>Due from Customers </h4>
          <p>Generate report for credits due from customers </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>PAYABLES</h4>
      </div>
      <div class="panel-body">
        <%=link_to payables_path(format: 'pdf') do %>
          <h4>Payable to Suppliers </h4>
          <p>Generate report for accounts payable to creditors </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>ACCOUNTING</h4>
      </div>
      <div class="panel-body">
        <%=link_to scope_to_date_accounting_balance_sheets_path(:from_date => Time.zone.now.beginning_of_month, :to_date => Time.zone.now.end_of_month, format: 'pdf') do %>
          <h4>Balance Sheet </h4>
          <p>Generate balance sheet report. </p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>AR COLLECTIONS</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to scope_to_date_credit_collections_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4> Daily AR Collections </h4>
              <p>Generate AR Collections of your business </p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_credit_collections_path(:from_date => Time.zone.now.beginning_of_month, :to_date => Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly AR Collections </h4>
              <p>Generate AR Collections of your business </p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_credit_collections_path(:from_date => Time.zone.now.beginning_of_year, :to_date => Time.zone.now.end_of_year, format: 'pdf') do %>
              <h4> Annual AR Collections </h4>
              <p>Generate AR Collections of your business </p>
            <% end %>
          </div>
        </div>
        <hr>
        <div class="col-md-6 col-md-offset-3 ">
          <h4> Custom AR Collection Report </h4>
          <%= form_tag({:action => "scope_to_date", controller: "credit_collections", format: 'pdf'}, {:method => :get})  do %>
            <div class="row">
              <div class="col-md-5">
                <div class="form-group">
                  <%= text_field_tag :from_date, @from_date, :class => 'datepicker-reporting form-control border-input', :placeholder => "From " %>
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-group">
                  <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker-reporting', :placeholder => "To " %>
                </div>
              </div>
              <div class="col-md-2">
                <button type="submit" class="btn btn-success active"> Go </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h4>INCOME STATEMENT</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%=link_to scope_to_date_accounting_income_statements_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4> Daily Income </h4>
              <p>Generate Income Statement of your business </p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_accounting_income_statements_path(:from_date => Time.zone.now.beginning_of_month, :to_date => Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4> Monthly Income </h4>
              <p>Generate Income Statement of your business </p>
            <% end %>
          </div>
          <div class="col-md-4">
            <%=link_to scope_to_date_accounting_income_statements_path(:from_date => Time.zone.now.beginning_of_year, :to_date => Time.zone.now.end_of_year, format: 'pdf') do %>
              <h4> Annual Income </h4>
              <p>Generate Income Statement of your business </p>
            <% end %>
          </div>
        </div>
        <hr>
        <div class="col-md-6 col-md-offset-3 ">
          <h4> Custom Income Statement Report </h4>
          <%= form_tag({:action => "scope_to_date", controller: "accounting/income_statements", format: 'pdf'}, {:method => :get})  do %>
            <div class="row">
              <div class="col-md-5">
                <div class="form-group">
                  <%= text_field_tag :from_date, @from_date, :class => 'datepicker-reporting form-control border-input', :placeholder => "From " %>
                </div>
              </div>
              <div class="col-md-5">
                <div class="form-group">
                  <%= text_field_tag :to_date, @to_date, :class => 'form-control border-input datepicker-reporting', :placeholder => "To " %>
                </div>
              </div>
              <div class="col-md-2">
                <button type="submit" class="btn btn-success active"> Go </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4>TRANSACTIONS</h4>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') do %>
              <h4>Daily</h4>
              <p>Generate transactions of your business for this day.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') do %>
              <h4>Weekly</h4>
              <p>Generate transactions of your business for this week.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%=link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') do %>
              <h4>Monthly</h4>
              <p>Generate transactions of your business for this month.</p>
            <% end %>
            <hr>
          </div>
          <div class="col-md-3">
            <%= link_to scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_year, to_date: Time.zone.now.end_of_year, format: 'pdf') do %>
              <h4>Yearly</h4>
              <p>Generate transactions of your business for this year.</p>
            <% end %>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>